### ISSUE TITLE
Add North Carolina imagery

### ISSUE THREAD

**Issue by Glodenox** [Glodenox/wme-om#104]
WMS: https://services.nconemap.gov/secure/services/Imagery/Orthoimagery_Latest/ImageServer/WMSServer?request=GetCapabilities&service=WMS

Licence to be verified. Wording seems to imply CC BY 4.0, but I couldn't immediately find this on the website. To check whether there's already an entry for this in the Waze attributions page.

**Comment by TheCre8r** [comment]
North Carolina is not on [Waze Legal Notices](https://www.waze.com/legal/notices). The NC OneMap attribution page is [here](https://www.nconemap.gov/pages/terms).

**Comment by Glodenox** [comment]
I had noticed that page, but it doesn't seem to explicitly mention the licence that applies. It just mentions how you should describe them if you provide attribution. At least the intention is clearly stated that this data is also available for private partners, so we don't have to assume the default situation (= copyright applies, can't use). So all in all, I think it should be safe to use this map as-is.
