### ISSUE TITLE
CIRB map deprecated

### ISSUE THREAD

**Issue by Glodenox** [Glodenox/wme-om#55]
The CIRB map of Brussels is indicating that the service access is deprecated. Probably they changed their URL. To investigate.

**Comment by rimeco** [comment]
WMS : nieuw UrbIS gegevens model  : http://geoservices-urbis.irisnet.be/geoserver/UrbisAdm/ows?Service=WMS&Request=GetCapabilities

source: http://www.geo.irisnet.be/nl/webservices/

**Comment by Glodenox** [comment]
Oh, my bad! I have already taken care of this in version 2.8.5 with commit e0f984f4b678e1fdb5618ccb8b3f27381817bca0, but apparently I forgot to close this issue.
I do notice that I used a slightly different URL, but the answer seems to be the same: https://geoservices-urbis.irisnet.be/geoserver/ows
