### ISSUE TITLE
Request: Orthophotos Wallonie

### ISSUE THREAD

**Issue by rimeco** [Glodenox/wme-om#56]
http://geoportail.wallonie.be/georeferentiel/orthophotos.
On the page for each serie (1971 - 2016) under "Accès" you can find the links to the services (WMS/WMTS)
example: http://geoservices.wallonie.be/arcgis/services/IMAGERIE/ORTHO_2016/MapServer/WMSServer?request=GetCapabilities&service=WMS

thx
Jean

**Comment by Glodenox** [comment]
I'm a bit hesitant about adding this map as the data is older than Google's satellite imagery and I'm not convinced [the license](http://geoportail.wallonie.be/files/documents/ConditionsSPW/LicServicesSPW.pdf) allows us to use this if we can't provide any attribution when we use this data somewhere. I think the license mostly refers to copying data, which we don't really do as we derive information from the data here, but I don't want to take any risk.

**Comment by rimeco** [comment]
Hi Tom,
Adding the different series makes it easier to spot changes. That's why I thought they could come in handy.
As regarding the license, in my opinion, it's only forbidden to mask or remove any watermark or other mention (should they provide one, which is not the case right now, as far as I know).
But anyway, if you find it too risky, or not useful enough, feel free to ignore the request altogether.
Gr.
Jean
(jeancleroy)

**Comment by Glodenox** [comment]
With the confirmation of SPW that we are allowed to refer stuff from their data for the map, I can go ahead with this request as well.

**Comment by Glodenox** [comment]
This map has now been added to the userscript.
