### ISSUE TITLE
New map (réseau routier régional)

### ISSUE THREAD

**Issue by skanico** [Glodenox/wme-om#64]
Hello,
Is is possible to add this http://geoportail.wallonie.be/catalogue/d26f16df-5326-4cd7-b768-709e75a25507.html to the plugin?
Thanks

**Comment by Glodenox** [comment]
I went through the technical aspects of this map and it seems relatively easy to add this. I am just not certain of the license under which it is supplied.
From what I understand from the [metadata page](http://metawal.wallonie.be/geonetwork/srv/fre/search?uuid=d26f16df-5326-4cd7-b768-709e75a25507) (more specifically, the section named "Conditions légales et contractuelles"), I think we need to request access before we can use the map within the WME.

Would you be willing to contact SPW via helpdesk.carto@spw.wallonie.be to make we are allowed to use their data to improve our maps?

**Comment by skanico** [comment]
Hello Tom,

No problem, I will ask them and forward their answer.

Have a good day,

Nicolas

**Comment by Glodenox** [comment]
Thanks for verifying this! I'll also use this information to unblock issue #56

**Comment by Glodenox** [comment]
This map has now been added to the userscript.
