### ISSUE TITLE
Query window comes behind selected segment while editing closure

### ISSUE THREAD

**Issue by Hipska** [Glodenox/wme-om#75]
Browser: Chrome 80
OM: 3.0.6

1. Query an object, so the result window comes up.
2. Minimize window
3. Select segment
4. Maximise window
5. Edit or create closure

<img width="1623" alt="image" src="https://user-images.githubusercontent.com/228588/74914578-f9ec5f80-53c2-11ea-86d0-d92ec107c60b.png">

**Comment by Glodenox** [comment]
That can happen if they set `z-index: 9999` as style...

I guess I'll set the `z-index` of the window at 10000 then 😂
