### ISSUE TITLE
Make layers selectable

### ISSUE THREAD

**Issue by Glodenox** [Glodenox/wme-om#8]
Most WMS services provide multiple layers which all provide additional data. Making these layers selectable in the map would be very handful.

**Comment by Hipska** [comment]
It would also be nice if you could activate multiple maps at the same time and have selection for opacity for each. Or should this be a separate request?

**Comment by Glodenox** [comment]
I look at that as a separate issue as having more layers from one map doesn't require adding a layer in the Waze map, but just demanding more data from the map source. So the complexity is quite a bit different. I'll split this off into a separate issue.

**Comment by Glodenox** [comment]
This was added in the latest release. It is not possible to set opacity for individual layers within a map, but that's a WONTFIX. A work-around for that is adding the same map twice, with only some layers visible and setting the opacity on those maps separately.
