### ISSUE TITLE
Enable from Layer menu does not work as intended

### ISSUE THREAD

**Issue by Hipska** [Glodenox/wme-om#80]
I think it's easier to explain with images.

Initial state after loading page:
<img width="360" alt="image" src="https://user-images.githubusercontent.com/228588/81598163-282c7a80-93c7-11ea-98ad-c8a72414a954.png">
After enabling:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/228588/81598575-d0dada00-93c7-11ea-9925-16a5412b5ff8.png">
After disabling:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/228588/81598620-e51ed700-93c7-11ea-82d7-1e7134bb0ccb.png">

Also note the different size of the checkbox and the OpenMaps layer group icon is not working.

Chrome 81 MacOS

**Comment by Glodenox** [comment]
The different sizes of checkboxes is something Waze can fix. I've created a bug report for that and that is somewhere in their development queue.

As for the other issue: I'll look into it. The way the new checkbox created by Waze works is still a bit of a mystery to me at the moment.

**Comment by Hipska** [comment]
So you have the same behaviour?

**Comment by Glodenox** [comment]
For me it works fine, but Paul also mentioned this issue when he has Fix UI reset the menu and sidebar. I did have to negate the "checked" state for it to work, which I found weird, so I'm pretty certain I'm doing something iffy there.

**Comment by Hipska** [comment]
If it might help, I don't have the FixUI plugin.

**Comment by Hipska** [comment]
Issue doesn't seem to occur anymore. Fixed?

**Comment by Glodenox** [comment]
The checkboxes thing was fixed, but I haven't changed anything in the logic for group toggling yet. I was actually just working on a rewrite of that part of the script.

**Comment by Hipska** [comment]
Group toggle icon also works..
